language: ruby
before_install: gem install bundler --version '1.8'
install: bundle install
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  slack: openfoodfacts:oicZXgD1SNoGCA6EXLK6CB7i
